name: Test against Rails main

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC
  workflow_dispatch:

jobs:
  specs:
    runs-on: ubuntu-latest

    name: Ruby ${{ matrix.ruby-version }}, ${{ matrix.gemfile }}

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.4'
        gemfile:
          - rails_main
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: zendesk/checkout@v4
      - name: Set up Ruby
        uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: RSpec
        run: bundle exec rspec
